insert into church_org(church_org_path, sort_order) values ('cemi', 2);
insert into church_org_details(church_org_id, locale, church_org_name) values (1, 'en', 'Christian Evangelical Mission International');
insert into church_org_details(church_org_id, locale, church_org_name) values (1, 'zh', '國際福音佈道會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (null, 1, null);
insert into church_org(church_org_path, sort_order) values ('america', 0);
insert into church_org_details(church_org_id, locale, church_org_name) values (2, 'en', 'CEMI in America');
insert into church_org_details(church_org_id, locale, church_org_name) values (2, 'zh', '美洲區會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (1, 2, null);
insert into church_org(church_org_path, sort_order) values ('america-east', 0);
insert into church_org_details(church_org_id, locale, church_org_name) values (3, 'en', 'CEM in East Coast');
insert into church_org_details(church_org_id, locale, church_org_name) values (3, 'zh', '美東分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (2, 3, null);
insert into church(church_path, sort_order) values ('brooklyn', 1);
insert into church_details(church_id, locale, church_name) values (1, 'en', 'ECMSI in Brooklyn');
insert into church_details(church_id, locale, church_name) values (1, 'zh', '佈路倫生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 1);
insert into church(church_path, sort_order) values ('chinatown', 2);
insert into church_details(church_id, locale, church_name) values (2, 'en', 'ECMSI in Chinatown');
insert into church_details(church_id, locale, church_name) values (2, 'zh', '中國城生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 2);
insert into church(church_path, sort_order) values ('queens', 3);
insert into church_details(church_id, locale, church_name) values (3, 'en', 'ECMSI in Queens');
insert into church_details(church_id, locale, church_name) values (3, 'zh', '皇后區生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 3);
insert into church(church_path, sort_order) values ('highlandpark', 5);
insert into church_details(church_id, locale, church_name) values (4, 'en', 'CEMC in Highland Park');
insert into church_details(church_id, locale, church_name) values (4, 'zh', '高原地生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 4);
insert into church(church_path, sort_order) values ('livingston', 6);
insert into church_details(church_id, locale, church_name) values (5, 'en', 'CEMC in Livingston');
insert into church_details(church_id, locale, church_name) values (5, 'zh', '活石園生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 5);
insert into church(church_path, sort_order) values ('murrayhill', 6);
insert into church_details(church_id, locale, church_name) values (6, 'en', 'CEMC in Murray Hill');
insert into church_details(church_id, locale, church_name) values (6, 'zh', '茉莉山生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 6);
insert into church(church_path, sort_order) values ('pearlriver', 7);
insert into church_details(church_id, locale, church_name) values (7, 'en', 'CEC in Pearl River');
insert into church_details(church_id, locale, church_name) values (7, 'zh', '珍珠河生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 7);
insert into church(church_path, sort_order) values ('towaco', 8);
insert into church_details(church_id, locale, church_name) values (8, 'en', 'CEMC in Towaco');
insert into church_details(church_id, locale, church_name) values (8, 'zh', '多華谷生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (3, null, 8);
insert into church_org(church_org_path, sort_order) values ('america-west', 2);
insert into church_org_details(church_org_id, locale, church_org_name) values (4, 'en', 'CEM in West Coast');
insert into church_org_details(church_org_id, locale, church_org_name) values (4, 'zh', '美西分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (2, 4, null);
insert into church(church_path, sort_order) values ('sandiego', 0);
insert into church_details(church_id, locale, church_name) values (9, 'en', 'IEC in San Diego');
insert into church_details(church_id, locale, church_name) values (9, 'zh', '聖地哥生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (4, null, 9);
insert into church(church_path, sort_order) values ('losangeles', 1);
insert into church_details(church_id, locale, church_name) values (10, 'en', 'IEC in Los Angeles');
insert into church_details(church_id, locale, church_name) values (10, 'zh', '洛杉磯生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (4, null, 10);
insert into church(church_path, sort_order) values ('sanfrancisco', 2);
insert into church_details(church_id, locale, church_name) values (11, 'en', 'IEC in San Francisco');
insert into church_details(church_id, locale, church_name) values (11, 'zh', '舊金山生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (4, null, 11);
insert into church(church_path, sort_order) values ('sanjose', 3);
insert into church_details(church_id, locale, church_name) values (12, 'en', 'IEC in San Jose');
insert into church_details(church_id, locale, church_name) values (12, 'zh', '聖河水生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (4, null, 12);
insert into church(church_path, sort_order) values ('sacramento', 4);
insert into church_details(church_id, locale, church_name) values (13, 'en', 'IEC in Sacramento');
insert into church_details(church_id, locale, church_name) values (13, 'zh', '沙加緬度生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (4, null, 13);
insert into church_org(church_org_path, sort_order) values ('europe', 2);
insert into church_org_details(church_org_id, locale, church_org_name) values (5, 'en', 'CEMI in Europe');
insert into church_org_details(church_org_id, locale, church_org_name) values (5, 'zh', '歐洲區會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (1, 5, null);
insert into church_org(church_org_path, sort_order) values ('hungary', -3);
insert into church_org_details(church_org_id, locale, church_org_name) values (6, 'en', 'CEM in Hungary');
insert into church_org_details(church_org_id, locale, church_org_name) values (6, 'zh', '匈牙利分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (5, 6, null);
insert into church(church_path, sort_order) values ('budapest', 0);
insert into church_details(church_id, locale, church_name) values (14, 'en', 'CEC in Budapest');
insert into church_details(church_id, locale, church_name) values (14, 'zh', '布達佩斯生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (6, null, 14);
insert into church_org(church_org_path, sort_order) values ('holland', 1);
insert into church_org_details(church_org_id, locale, church_org_name) values (7, 'en', 'CEM in Holland');
insert into church_org_details(church_org_id, locale, church_org_name) values (7, 'zh', '荷蘭分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (5, 7, null);
insert into church(church_path, sort_order) values ('groningen', 0);
insert into church_details(church_id, locale, church_name) values (15, 'en', 'CEC in Groningen');
insert into church_details(church_id, locale, church_name) values (15, 'zh', '高寧根生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 15);
insert into church(church_path, sort_order) values ('enschede', 0);
insert into church_details(church_id, locale, church_name) values (16, 'en', 'CEC in Enschede');
insert into church_details(church_id, locale, church_name) values (16, 'zh', '恩慈地生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 16);
insert into church(church_path, sort_order) values ('arnhem', 0);
insert into church_details(church_id, locale, church_name) values (17, 'en', 'CEC in Arnhem');
insert into church_details(church_id, locale, church_name) values (17, 'zh', '安恆基督教生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 17);
insert into church(church_path, sort_order) values ('veenendaal', 0);
insert into church_details(church_id, locale, church_name) values (18, 'en', 'CEC in Veenendaal');
insert into church_details(church_id, locale, church_name) values (18, 'zh', '福臨道基督教生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 18);
insert into church(church_path, sort_order) values ('leeuwarden', 0);
insert into church_details(church_id, locale, church_name) values (19, 'en', 'CEC in Leeuwarden');
insert into church_details(church_id, locale, church_name) values (19, 'zh', '樂華城基督教生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 19);
insert into church(church_path, sort_order) values ('rotterdam', 1);
insert into church_details(church_id, locale, church_name) values (20, 'en', 'CEC in Rotterdam');
insert into church_details(church_id, locale, church_name) values (20, 'zh', '鹿特丹生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 20);
insert into church(church_path, sort_order) values ('denhaag', 2);
insert into church_details(church_id, locale, church_name) values (21, 'en', 'CEC in Den Haag');
insert into church_details(church_id, locale, church_name) values (21, 'zh', '海牙生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 21);
insert into church(church_path, sort_order) values ('utrecht', 3);
insert into church_details(church_id, locale, church_name) values (22, 'en', 'CEC in Utrecht');
insert into church_details(church_id, locale, church_name) values (22, 'zh', '烏特勒生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 22);
insert into church(church_path, sort_order) values ('amsterdam', 4);
insert into church_details(church_id, locale, church_name) values (23, 'en', 'CEC in Amsterdam');
insert into church_details(church_id, locale, church_name) values (23, 'zh', '荷京生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 23);
insert into church(church_path, sort_order) values ('zwolle', 5);
insert into church_details(church_id, locale, church_name) values (24, 'en', 'CEC in Zwolle');
insert into church_details(church_id, locale, church_name) values (24, 'zh', '思活路生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 24);
insert into church(church_path, sort_order) values ('breda', 6);
insert into church_details(church_id, locale, church_name) values (25, 'en', 'CEC in Breda');
insert into church_details(church_id, locale, church_name) values (25, 'zh', '百利達生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 25);
insert into church(church_path, sort_order) values ('bergenopzoom', 7);
insert into church_details(church_id, locale, church_name) values (26, 'en', 'CEC in Bergen Op Zoom');
insert into church_details(church_id, locale, church_name) values (26, 'zh', '百合山生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (7, null, 26);
insert into church_org(church_org_path, sort_order) values ('spain', 2);
insert into church_org_details(church_org_id, locale, church_org_name) values (8, 'en', 'CEM in Spain');
insert into church_org_details(church_org_id, locale, church_org_name) values (8, 'zh', '西班牙分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (5, 8, null);
insert into church(church_path, sort_order) values ('madrid', 1);
insert into church_details(church_id, locale, church_name) values (27, 'en', 'CEC in Madrid');
insert into church_details(church_id, locale, church_name) values (27, 'zh', '馬德里生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 27);
insert into church(church_path, sort_order) values ('valencia', 2);
insert into church_details(church_id, locale, church_name) values (28, 'en', 'CEC in Valencia');
insert into church_details(church_id, locale, church_name) values (28, 'zh', '瓦倫西亞生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 28);
insert into church(church_path, sort_order) values ('benidorm', 3);
insert into church_details(church_id, locale, church_name) values (29, 'en', 'CEC in Benidorm');
insert into church_details(church_id, locale, church_name) values (29, 'zh', '貝妮東生命堂 ');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 29);
insert into church(church_path, sort_order) values ('alicante', 4);
insert into church_details(church_id, locale, church_name) values (30, 'en', 'CEC in Alicante');
insert into church_details(church_id, locale, church_name) values (30, 'zh', '愛麗甘地生命堂 ');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 30);
insert into church(church_path, sort_order) values ('canaria', 5);
insert into church_details(church_id, locale, church_name) values (31, 'en', 'CEC in Gran Canaria ');
insert into church_details(church_id, locale, church_name) values (31, 'zh', '加納利亞生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 31);
insert into church(church_path, sort_order) values ('southmadrid', 6);
insert into church_details(church_id, locale, church_name) values (32, 'en', 'CEC in South Madrid');
insert into church_details(church_id, locale, church_name) values (32, 'zh', '馬德里南區生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 32);
insert into church(church_path, sort_order) values ('barcelona', 7);
insert into church_details(church_id, locale, church_name) values (33, 'en', 'CEC in Barcelona');
insert into church_details(church_id, locale, church_name) values (33, 'zh', '巴塞羅那生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 33);
insert into church(church_path, sort_order) values ('fuenlabrada', 8);
insert into church_details(church_id, locale, church_name) values (34, 'en', 'CEC in Fuenlabrada');
insert into church_details(church_id, locale, church_name) values (34, 'zh', '福恩城生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (8, null, 34);
insert into church_org(church_org_path, sort_order) values ('portugal', 3);
insert into church_org_details(church_org_id, locale, church_org_name) values (9, 'en', 'CEM in Portugal');
insert into church_org_details(church_org_id, locale, church_org_name) values (9, 'zh', '葡萄牙分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (5, 9, null);
insert into church(church_path, sort_order) values ('portoalto', 0);
insert into church_details(church_id, locale, church_name) values (35, 'en', 'CEC in Porto Alto');
insert into church_details(church_id, locale, church_name) values (35, 'zh', '播道歐多');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (9, null, 35);
insert into church(church_path, sort_order) values ('lisbon', 1);
insert into church_details(church_id, locale, church_name) values (36, 'en', 'CEC in Lisbon');
insert into church_details(church_id, locale, church_name) values (36, 'zh', '里斯本生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (9, null, 36);
insert into church(church_path, sort_order) values ('porto', 2);
insert into church_details(church_id, locale, church_name) values (37, 'en', 'CEC in Porto');
insert into church_details(church_id, locale, church_name) values (37, 'zh', '波爾圖生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (9, null, 37);
insert into church(church_path, sort_order) values ('mindelo', 3);
insert into church_details(church_id, locale, church_name) values (38, 'en', 'CEC in Mindelo');
insert into church_details(church_id, locale, church_name) values (38, 'zh', '明德路生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (9, null, 38);
insert into church_org(church_org_path, sort_order) values ('france', 4);
insert into church_org_details(church_org_id, locale, church_org_name) values (10, 'en', 'CEM in France');
insert into church_org_details(church_org_id, locale, church_org_name) values (10, 'zh', '法國分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (5, 10, null);
insert into church(church_path, sort_order) values ('paris', 1);
insert into church_details(church_id, locale, church_name) values (39, 'en', 'CEC in Paris');
insert into church_details(church_id, locale, church_name) values (39, 'zh', '巴黎生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (10, null, 39);
insert into church_org(church_org_path, sort_order) values ('belgium', 5);
insert into church_org_details(church_org_id, locale, church_org_name) values (11, 'en', 'CEM in Belgium');
insert into church_org_details(church_org_id, locale, church_org_name) values (11, 'zh', '比利時分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (5, 11, null);
insert into church(church_path, sort_order) values ('antwerpen', 1);
insert into church_details(church_id, locale, church_name) values (40, 'en', 'CEC in Antwerpen');
insert into church_details(church_id, locale, church_name) values (40, 'zh', '安慰城生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (11, null, 40);
insert into church(church_path, sort_order) values ('brussels', 2);
insert into church_details(church_id, locale, church_name) values (41, 'en', 'CEC in Brussels');
insert into church_details(church_id, locale, church_name) values (41, 'zh', '布魯塞爾生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (11, null, 41);
insert into church(church_path, sort_order) values ('gent', 3);
insert into church_details(church_id, locale, church_name) values (42, 'en', 'CEC in Gent');
insert into church_details(church_id, locale, church_name) values (42, 'zh', '根特生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (11, null, 42);
insert into church_org(church_org_path, sort_order) values ('italy', 6);
insert into church_org_details(church_org_id, locale, church_org_name) values (12, 'en', 'CEM in Italy');
insert into church_org_details(church_org_id, locale, church_org_name) values (12, 'zh', '義大利分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (5, 12, null);
insert into church(church_path, sort_order) values ('prato', -3);
insert into church_details(church_id, locale, church_name) values (43, 'en', 'CEMC in Prato');
insert into church_details(church_id, locale, church_name) values (43, 'zh', '普拉托基督教生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (12, null, 43);
insert into church(church_path, sort_order) values ('milan', 0);
insert into church_details(church_id, locale, church_name) values (44, 'en', 'CEC in Milan');
insert into church_details(church_id, locale, church_name) values (44, 'zh', '米蘭生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (12, null, 44);
insert into church_org(church_org_path, sort_order) values ('asia', 3);
insert into church_org_details(church_org_id, locale, church_org_name) values (13, 'en', 'CEMI in Asia');
insert into church_org_details(church_org_id, locale, church_org_name) values (13, 'zh', '亞洲區會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (1, 13, null);
insert into church_org(church_org_path, sort_order) values ('japan', -5);
insert into church_org_details(church_org_id, locale, church_org_name) values (14, 'en', 'CEM in Japan');
insert into church_org_details(church_org_id, locale, church_org_name) values (14, 'zh', '日本分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (13, 14, null);
insert into church(church_path, sort_order) values ('nagoya', 0);
insert into church_details(church_id, locale, church_name) values (45, 'en', 'CEC in Nagoya');
insert into church_details(church_id, locale, church_name) values (45, 'zh', '名古屋生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (14, null, 45);
insert into church(church_path, sort_order) values ('kobe', 0);
insert into church_details(church_id, locale, church_name) values (46, 'en', 'CEC in Kobe');
insert into church_details(church_id, locale, church_name) values (46, 'zh', '神戶生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (14, null, 46);
insert into church(church_path, sort_order) values ('osaka', 0);
insert into church_details(church_id, locale, church_name) values (47, 'en', 'CEC in Osaka');
insert into church_details(church_id, locale, church_name) values (47, 'zh', 'Osaka (zh)');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (14, null, 47);
insert into church_org(church_org_path, sort_order) values ('taiwan', 2);
insert into church_org_details(church_org_id, locale, church_org_name) values (15, 'en', 'CEM in Taiwan');
insert into church_org_details(church_org_id, locale, church_org_name) values (15, 'zh', '臺灣分會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (13, 15, null);
insert into church(church_path, sort_order) values ('taipei', 1);
insert into church_details(church_id, locale, church_name) values (48, 'en', 'CEC in Taipei');
insert into church_details(church_id, locale, church_name) values (48, 'zh', '臺北生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (15, null, 48);
insert into church_org(church_org_path, sort_order) values ('africa', 4);
insert into church_org_details(church_org_id, locale, church_org_name) values (16, 'en', 'CEMI in Africa');
insert into church_org_details(church_org_id, locale, church_org_name) values (16, 'zh', '非洲區會');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (1, 16, null);
insert into church(church_path, sort_order) values ('parownorth', 0);
insert into church_details(church_id, locale, church_name) values (49, 'en', 'CEC in Parow-Noord');
insert into church_details(church_id, locale, church_name) values (49, 'zh', '八福城生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (16, null, 49);
insert into church(church_path, sort_order) values ('capetown', 1);
insert into church_details(church_id, locale, church_name) values (50, 'en', 'CEC in Cape Town');
insert into church_details(church_id, locale, church_name) values (50, 'zh', '開普敦生命堂');
insert into church_hierarchy(parent_church_org_id, church_org_id, church_id) values (16, null, 50);
